//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.KunaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KunaService.IKunaServise")]
    public interface IKunaServise {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTimestamp", ReplyAction="http://tempuri.org/IKunaServise/GetTimestampResponse")]
        string GetTimestamp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTimestamp", ReplyAction="http://tempuri.org/IKunaServise/GetTimestampResponse")]
        System.Threading.Tasks.Task<string> GetTimestampAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTickerline", ReplyAction="http://tempuri.org/IKunaServise/GetTickerlineResponse")]
        string GetTickerline(string marketPair);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTickerline", ReplyAction="http://tempuri.org/IKunaServise/GetTickerlineResponse")]
        System.Threading.Tasks.Task<string> GetTickerlineAsync(string marketPair);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetOrderBook", ReplyAction="http://tempuri.org/IKunaServise/GetOrderBookResponse")]
        string GetOrderBook(string marketPair);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetOrderBook", ReplyAction="http://tempuri.org/IKunaServise/GetOrderBookResponse")]
        System.Threading.Tasks.Task<string> GetOrderBookAsync(string marketPair);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTrades", ReplyAction="http://tempuri.org/IKunaServise/GetTradesResponse")]
        string GetTrades(string marketPair);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTrades", ReplyAction="http://tempuri.org/IKunaServise/GetTradesResponse")]
        System.Threading.Tasks.Task<string> GetTradesAsync(string marketPair);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKunaServiseChannel : TestApp.KunaService.IKunaServise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KunaServiseClient : System.ServiceModel.ClientBase<TestApp.KunaService.IKunaServise>, TestApp.KunaService.IKunaServise {
        
        public KunaServiseClient() {
        }
        
        public KunaServiseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KunaServiseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KunaServiseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KunaServiseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTimestamp() {
            return base.Channel.GetTimestamp();
        }
        
        public System.Threading.Tasks.Task<string> GetTimestampAsync() {
            return base.Channel.GetTimestampAsync();
        }
        
        public string GetTickerline(string marketPair) {
            return base.Channel.GetTickerline(marketPair);
        }
        
        public System.Threading.Tasks.Task<string> GetTickerlineAsync(string marketPair) {
            return base.Channel.GetTickerlineAsync(marketPair);
        }
        
        public string GetOrderBook(string marketPair) {
            return base.Channel.GetOrderBook(marketPair);
        }
        
        public System.Threading.Tasks.Task<string> GetOrderBookAsync(string marketPair) {
            return base.Channel.GetOrderBookAsync(marketPair);
        }
        
        public string GetTrades(string marketPair) {
            return base.Channel.GetTrades(marketPair);
        }
        
        public System.Threading.Tasks.Task<string> GetTradesAsync(string marketPair) {
            return base.Channel.GetTradesAsync(marketPair);
        }
    }
}
