//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IKunaServise")]
    public interface IKunaServise {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTimestamp", ReplyAction="http://tempuri.org/IKunaServise/GetTimestampResponse")]
        string GetTimestamp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKunaServise/GetTimestamp", ReplyAction="http://tempuri.org/IKunaServise/GetTimestampResponse")]
        System.Threading.Tasks.Task<string> GetTimestampAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKunaServiseChannel : TestApp.ServiceReference2.IKunaServise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KunaServiseClient : System.ServiceModel.ClientBase<TestApp.ServiceReference2.IKunaServise>, TestApp.ServiceReference2.IKunaServise {
        
        public KunaServiseClient() {
        }
        
        public KunaServiseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KunaServiseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KunaServiseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KunaServiseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTimestamp() {
            return base.Channel.GetTimestamp();
        }
        
        public System.Threading.Tasks.Task<string> GetTimestampAsync() {
            return base.Channel.GetTimestampAsync();
        }
    }
}
